### ISSUE TITLE
Isnet.isIP is not a function

### ISSUE THREAD

**Issue by SateeshKorukonda** [ip2location/ip2location-nodejs#18]
I installed ip2location-nodejs in my next js project. And when tried to fetch the country details using IP information. i received an error in console stating "net.isIP is not a function". Below is present in downloaded module of ip2location-nodejs
![image](https://user-images.githubusercontent.com/42402306/228536360-bc1c0a5f-e2da-4707-a534-e6d9e3fb3e48.png)

**Comment by ip2location** [comment]
That should be a core part of Node.js https://nodejs.org/api/net.html#netisipinput which you should have if you're running the code on the server side. You cannot run the code on client side as the library is meant for server side use by Node.js.
