### ISSUE TITLE
TypeScript type definitions are incorrect for latitude / longitude

### ISSUE THREAD

**Issue by JimDabell** [ip2location/ip2location-nodejs#23]
You return numbers for these fields but your type definitions specify that you return strings, so the type definitions are incorrect in normal cases. The situation is complicated a bit though because you return an object with `"?"` as values in error conditions, so sometimes they are strings and sometimes numbers.

The best approach is to throw an error instead of returning an invalid object full of sentinel values, but if you aren’t interested in changing the API, then marking the latitude / longitude fields as numbers instead of strings is the smallest fix for this problem.

**Comment by ip2location** [comment]
We are also returning error messages in all of the fields, hence the need to maintain them as strings.

**Comment by JimDabell** [comment]
But you return `number` in normal operation, making `string` incorrect. If you want to continue to return both, then declare it as `number | string`. But `string` by itself is unambiguously incorrect and shows up as an error when writing code that calls your library and gets a `number` in return. This is a bug.

**Comment by ip2location** [comment]
We've updated the type definitions. Please check and see if you still encounter errors.
